# Generated by Django 6.0.1 on 2026-01-17 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="색상명")),
                (
                    "code",
                    models.CharField(
                        help_text="예: #FF0000", max_length=10, verbose_name="색상코드"
                    ),
                ),
            ],
            options={
                "verbose_name": "색상",
                "verbose_name_plural": "색상",
                "db_table": "colors",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                ("name", models.CharField(max_length=20, verbose_name="사이즈명")),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬순서"),
                ),
            ],
            options={
                "verbose_name": "사이즈",
                "verbose_name_plural": "사이즈",
                "db_table": "sizes",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                ("image_url", models.URLField(verbose_name="이미지 URL")),
                (
                    "is_thumbnail",
                    models.BooleanField(default=False, verbose_name="썸네일 여부"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬순서"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="상품",
                    ),
                ),
            ],
            options={
                "verbose_name": "이미지",
                "verbose_name_plural": "이미지",
                "db_table": "images",
                "ordering": ["-is_thumbnail", "display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DetailedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="재고")),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detailed_products",
                        to="products.color",
                        verbose_name="색상",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detailed_products",
                        to="products.product",
                        verbose_name="상품",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detailed_products",
                        to="products.size",
                        verbose_name="사이즈",
                    ),
                ),
            ],
            options={
                "verbose_name": "상세 상품",
                "verbose_name_plural": "상세 상품",
                "db_table": "detailed_products",
                "ordering": ["id"],
                "unique_together": {("product", "color", "size")},
            },
        ),
    ]
