# Generated by Django 6.0.1 on 2026-01-17 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0004_add_detailed_domain"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="detailed_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.detailedproduct",
                verbose_name="상세상품",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
                verbose_name="상품",
            ),
        ),
    ]
