# Generated by Django 6.0.1 on 2026-01-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_wishlist"),
        ("products", "0004_add_detailed_domain"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("detailed_product__isnull", True), ("product__isnull", False)),
                    models.Q(("detailed_product__isnull", False), ("product__isnull", True)),
                    _connector="OR",
                ),
                name="exactly_one_product_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("product__isnull", False)),
                fields=("cart", "product"),
                name="unique_cart_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("detailed_product__isnull", False)),
                fields=("cart", "detailed_product"),
                name="unique_cart_detailed_product",
            ),
        ),
    ]
