# Generated by Django 6.0.1 on 2026-01-17 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_options_alter_user_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "사용자", "verbose_name_plural": "사용자 목록"},
        ),
        migrations.AddField(
            model_name="user",
            name="address1",
            field=models.CharField(blank=True, max_length=255, verbose_name="주소1"),
        ),
        migrations.AddField(
            model_name="user",
            name="address2",
            field=models.CharField(blank=True, max_length=255, verbose_name="주소2"),
        ),
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="생년월일"),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "남성"), ("F", "여성")],
                max_length=1,
                verbose_name="성별",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="전화번호 형식은 010-1234-5678 이어야 합니다.",
                        regex="^01[0-9]-\\d{3,4}-\\d{4}$",
                    )
                ],
                verbose_name="전화번호",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=50, verbose_name="사용자명"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="이메일"),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=150, verbose_name="이름"),
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
